#!/usr/bin/env ts-node
/**
 * CRAFT Shim Generator - Skill #2
 * Generate Android API shim implementations with boilerplate code
 */

import * as fs from 'fs';
import * as path from 'path';

interface ShimSpec {
  className: string;      // e.g., "android.graphics.Paint"
  methods: MethodSpec[];
  extends?: string;       // Parent class
  fields?: FieldSpec[];
}

interface MethodSpec {
  name: string;
  descriptor: string;
  returnType: string;
  params: string[];
  isStatic?: boolean;
}

interface FieldSpec {
  name: string;
  type: string;
  isStatic?: boolean;
}

function printUsage() {
  console.log(`
CRAFT Shim Generator

Usage: npx ts-node tools/gen_shim.ts <class-name> [options]

Arguments:
  <class-name>          Full Android class name (e.g., android.graphics.Paint)

Options:
  --method <spec>       Add method (format: name:descriptor:returnType)
  --extends <class>     Parent class name
  --field <spec>        Add field (format: name:type)
  --interactive         Interactive mode (prompts for details)
  --help               Show this help message

Examples:
  # Generate basic shim
  npx ts-node tools/gen_shim.ts android.graphics.Paint

  # With methods and parent class
  npx ts-node tools/gen_shim.ts android.graphics.Paint \\
    --extends android.view.View \\
    --method "setColor:(I)V:void" \\
    --method "getColor:()I:number"

  # Interactive mode
  npx ts-node tools/gen_shim.ts android.graphics.Paint --interactive
`);
}

function classNameToPath(className: string): string {
  // Convert android.graphics.Paint to android/graphics/paint.ts
  return className.replace(/\./g, '/').toLowerCase() + '.ts';
}

function classNameToDescriptor(className: string): string {
  // Convert android.graphics.Paint to Landroid/graphics/Paint;
  return 'L' + className.replace(/\./g, '/') + ';';
}

function generateShimCode(spec: ShimSpec): string {
  const descriptor = classNameToDescriptor(spec.className);
  const simpleName = spec.className.split('.').pop()!;
  const extendsDescriptor = spec.extends ? classNameToDescriptor(spec.extends) : 'Ljava/lang/Object;';

  const code = `/**
 * Shim for ${spec.className}
 * Generated by CRAFT Shim Generator
 */

import { ShimRegistry } from '../../interpreter/shim_registry';
import { Heap } from '../../interpreter/heap';
import { Interpreter } from '../../interpreter/interpreter';
import { Value } from '../../core/types';
import { log } from '../../core/utils';

export const ${simpleName.toUpperCase()}_CLASS = '${descriptor}';

/**
 * Register ${simpleName} shim methods
 */
export function register${simpleName}Shim(registry: ShimRegistry): void {
  log('shim', 'info', \`Registering ${simpleName} shim\`);

  // Constructor
  registry.register(
    ${simpleName.toUpperCase()}_CLASS,
    '<init>',
    '()V',
    (interp: Interpreter, heap: Heap, thisRef: number, args: Value[]): Value => {
      log('shim', 'debug', \`${simpleName}.<init>()\`);

      // Call parent constructor
      const parentConstructor = registry.getMethod('${extendsDescriptor}', '<init>', '()V');
      if (parentConstructor) {
        parentConstructor(interp, heap, thisRef, args);
      }

      // Initialize fields${spec.fields ? '\n' + spec.fields.map(f =>
        `      heap.setField(thisRef, '${f.name}', { type: '${getValueType(f.type)}', value: ${getDefaultValue(f.type)} });`
      ).join('\n') : ''}

      return { type: 'null' };
    }
  );

${spec.methods.map(method => generateMethodShim(simpleName, method)).join('\n\n')}
}

${spec.fields && spec.fields.length > 0 ? `
/**
 * ${simpleName} field definitions
 */
interface ${simpleName}Fields {
${spec.fields.map(f => `  ${f.name}: ${f.type};`).join('\n')}
}
` : ''}
`;

  return code;
}

function generateMethodShim(className: string, method: MethodSpec): string {
  const paramList = method.params.map((p, i) => `args[${i}]`).join(', ');

  return `  // ${method.name}${method.descriptor}
  registry.register(
    ${className.toUpperCase()}_CLASS,
    '${method.name}',
    '${method.descriptor}',
    (interp: Interpreter, heap: Heap, thisRef: number, args: Value[]): Value => {
      log('shim', 'debug', \`${className}.${method.name}()\`);

      // TODO: Implement ${method.name} logic
      ${method.returnType === 'void' ?
        'return { type: \'null\' };' :
        `return { type: '${getValueType(method.returnType)}', value: ${getDefaultValue(method.returnType)} };`
      }
    }
  );`;
}

function getValueType(type: string): string {
  if (type.includes('int') || type === 'boolean' || type === 'byte' || type === 'short' || type === 'char') {
    return 'int';
  }
  if (type === 'long') return 'long';
  if (type === 'float') return 'float';
  if (type === 'double') return 'double';
  return 'object';
}

function getDefaultValue(type: string): string {
  if (type.includes('int') || type === 'boolean') return '0';
  if (type === 'long') return '0n';
  if (type === 'float' || type === 'double') return '0.0';
  return '0';
}

function generateTestCode(spec: ShimSpec): string {
  const simpleName = spec.className.split('.').pop()!;

  return `/**
 * Tests for ${spec.className} shim
 * Generated by CRAFT Shim Generator
 */

import { Interpreter } from '../../../src/interpreter/interpreter';
import { Heap } from '../../../src/interpreter/heap';
import { DexParser } from '../../../src/parser/dex_parser';
import { initializeShimRegistry } from '../../../src/interpreter/shim_init';

describe('${simpleName} Shim', () => {
  let heap: Heap;
  let registry: ReturnType<typeof initializeShimRegistry>;

  beforeEach(() => {
    heap = new Heap();
    registry = initializeShimRegistry();
  });

  test('constructor creates instance', () => {
    const constructor = registry.getMethod('${classNameToDescriptor(spec.className)}', '<init>', '()V');
    expect(constructor).toBeDefined();

    const ref = heap.allocateObject('${classNameToDescriptor(spec.className)}');
    const result = constructor!(null as any, heap, ref, []);

    expect(result.type).toBe('null');
  });

${spec.methods.slice(0, 2).map(method => `
  test('${method.name} method works', () => {
    const method = registry.getMethod('${classNameToDescriptor(spec.className)}', '${method.name}', '${method.descriptor}');
    expect(method).toBeDefined();

    const ref = heap.allocateObject('${classNameToDescriptor(spec.className)}');
    // TODO: Add test implementation
  });`).join('\n')}
});
`;
}

function generateIndexUpdate(spec: ShimSpec): string {
  const simpleName = spec.className.split('.').pop()!;
  const relativePath = classNameToPath(spec.className);

  return `
// Add this to the appropriate index.ts file:
import { register${simpleName}Shim } from './${relativePath.split('/').pop()?.replace('.ts', '')}';

// In the registration function:
register${simpleName}Shim(registry);
`;
}

function writeShimFiles(spec: ShimSpec): void {
  const basePath = path.join(__dirname, '..', 'src', 'shim');
  const relativePath = classNameToPath(spec.className);
  const fullPath = path.join(basePath, relativePath);
  const testPath = path.join(__dirname, '..', 'test', 'unit', 'shim', relativePath);

  // Create directories
  const dir = path.dirname(fullPath);
  const testDir = path.dirname(testPath);

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  if (!fs.existsSync(testDir)) {
    fs.mkdirSync(testDir, { recursive: true });
  }

  // Write shim file
  const shimCode = generateShimCode(spec);
  fs.writeFileSync(fullPath, shimCode);
  console.log(`[CRAFT][GenShim][Success] Created shim: ${fullPath}`);

  // Write test file
  const testCode = generateTestCode(spec);
  fs.writeFileSync(testPath, testCode);
  console.log(`[CRAFT][GenShim][Success] Created test: ${testPath}`);

  // Print index update instructions
  console.log('\n[CRAFT][GenShim][Info] Update index.ts:');
  console.log(generateIndexUpdate(spec));
}

function parseMethodSpec(spec: string): MethodSpec {
  // Format: name:descriptor:returnType
  const parts = spec.split(':');
  if (parts.length !== 3) {
    throw new Error(`Invalid method spec: ${spec}`);
  }

  return {
    name: parts[0],
    descriptor: parts[1],
    returnType: parts[2],
    params: [] // TODO: Parse from descriptor
  };
}

function parseFieldSpec(spec: string): FieldSpec {
  // Format: name:type
  const parts = spec.split(':');
  if (parts.length !== 2) {
    throw new Error(`Invalid field spec: ${spec}`);
  }

  return {
    name: parts[0],
    type: parts[1]
  };
}

function main() {
  const args = process.argv.slice(2);

  if (args.length === 0 || args.includes('--help')) {
    printUsage();
    process.exit(0);
  }

  const className = args[0];
  const spec: ShimSpec = {
    className,
    methods: [],
    fields: []
  };

  for (let i = 1; i < args.length; i++) {
    switch (args[i]) {
      case '--method':
        spec.methods.push(parseMethodSpec(args[++i]));
        break;
      case '--extends':
        spec.extends = args[++i];
        break;
      case '--field':
        spec.fields!.push(parseFieldSpec(args[++i]));
        break;
      case '--interactive':
        console.log('[CRAFT][GenShim][Info] Interactive mode not yet implemented');
        break;
    }
  }

  console.log(`[CRAFT][GenShim][Info] Generating shim for ${className}`);
  writeShimFiles(spec);
  console.log('[CRAFT][GenShim][Success] Shim generation complete! ✅');
}

main();
