#!/usr/bin/env ts-node
/**
 * CRAFT Gen Integration Test - Skill #11
 * Scaffold integration test files for APK → Activity → UI flows.
 */

import * as fs from 'fs';
import * as path from 'path';

function printUsage(): void {
  console.log(`
[CRAFT][GenIntegrationTest] Integration Test Scaffolder

Usage: npm run gen-integration-test <name> [options]

Options:
  --fixture <path>        APK/DEX fixture to use
  --activity <class>      Activity class name (e.g., Lcom/example/MainActivity;)
  --output <path>         Output test file path
  --runtime               Generate CraftRuntime-based test (APK)
  --interpreter           Generate Interpreter-based test (DEX) (default)
  --help                  Show this help

Examples:
  npm run gen-integration-test hello-world
  npm run gen-integration-test login-flow -- --fixture test/fixtures/login.apk --runtime
  npm run gen-integration-test calculator -- --activity "Lcom/example/CalcActivity;"
`);
}

function toClassName(name: string): string {
  return name
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function generateRuntimeTest(
  name: string,
  fixturePath: string,
  activityClass: string
): string {
  const className = toClassName(name);
  return `/**
 * Integration test: ${className}
 * Generated by: npm run gen-integration-test ${name}
 */

import { CraftRuntime } from '../../src/runtime';
import * as fs from 'fs';

describe('Integration: ${className}', () => {
  let runtime: CraftRuntime;

  beforeEach(() => {
    runtime = new CraftRuntime();
    const apkData = fs.readFileSync('${fixturePath}');
    runtime.loadAPK(new Uint8Array(apkData));
  });

  afterEach(() => runtime.shutdown());

  test('creates activity and initializes', () => {
    const activityRef = runtime.createActivity('${activityClass}');
    expect(activityRef).toBeGreaterThan(0);
  });

  test('full lifecycle: create -> resume -> pause -> destroy', () => {
    runtime.createActivity('${activityClass}');
    runtime.resumeActivity();

    const state = runtime.getViewState();
    expect(state).toBeDefined();

    runtime.pauseActivity();
    runtime.destroyActivity();
  });

  test('renders UI after resume', () => {
    runtime.createActivity('${activityClass}');
    runtime.resumeActivity();

    const state = runtime.getViewState();
    // TODO: Add specific assertions about the view tree
    expect(state).toBeDefined();
  });
});
`;
}

function generateInterpreterTest(
  name: string,
  fixturePath: string,
  activityClass: string
): string {
  const className = toClassName(name);
  return `/**
 * Integration test: ${className}
 * Generated by: npm run gen-integration-test ${name}
 */

import { DexParser } from '../../src/parser/dex_parser';
import { Interpreter } from '../../src/interpreter/interpreter';
import { Heap } from '../../src/interpreter/heap';
import { initializeShimRegistry } from '../../src/interpreter/shim_init';
import { objectRef, NULL_VALUE } from '../../src/core/types';
import * as fs from 'fs';

describe('Integration: ${className}', () => {
  let dex: DexParser;
  let heap: Heap;
  let interpreter: Interpreter;

  beforeEach(() => {
    const dexData = new Uint8Array(fs.readFileSync('${fixturePath}'));
    dex = new DexParser(dexData);
    heap = new Heap();
    const shimRegistry = initializeShimRegistry();
    interpreter = new Interpreter(dex, heap, shimRegistry);
  });

  test('creates activity via shims', () => {
    // Allocate Activity instance
    const activityRef = heap.allocate('${activityClass}');

    // Call Activity.<init>
    const initResult = interpreter.invoke(
      '${activityClass}', '<init>', '()V',
      [objectRef(activityRef)]
    );
    expect(initResult.type).toBe('null');

    // Call Activity.onCreate(null)
    const onCreateResult = interpreter.invoke(
      '${activityClass}', 'onCreate', '(Landroid/os/Bundle;)V',
      [objectRef(activityRef), NULL_VALUE]
    );
    expect(onCreateResult.type).toBe('null');
  });

  test('verifies activity state after creation', () => {
    const activityRef = heap.allocate('${activityClass}');
    interpreter.invoke('${activityClass}', '<init>', '()V', [objectRef(activityRef)]);

    // TODO: Add specific assertions about activity state
    const contentView = heap.getField(activityRef, 'mContentView');
    expect(contentView.type).toBe('null'); // No content view set yet
  });

  // TODO: Add more test cases specific to this activity
});
`;
}

function main(): void {
  const args = process.argv.slice(2);

  if (args.length === 0 || args.includes('--help')) {
    printUsage();
    process.exit(0);
  }

  let name = '';
  let fixturePath = '';
  let activityClass = 'Landroid/app/Activity;';
  let outputPath = '';
  let useRuntime = false;

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--fixture':
        fixturePath = args[++i] || '';
        break;
      case '--activity':
        activityClass = args[++i] || '';
        break;
      case '--output':
        outputPath = args[++i] || '';
        break;
      case '--runtime':
        useRuntime = true;
        break;
      case '--interpreter':
        useRuntime = false;
        break;
      default:
        if (!args[i].startsWith('-') && !name) {
          name = args[i];
        }
        break;
    }
  }

  if (!name) {
    console.error('[CRAFT][GenIntegrationTest][Error] No test name specified');
    process.exit(1);
  }

  if (!fixturePath) {
    fixturePath = useRuntime
      ? `test/fixtures/${name}.apk`
      : `test/fixtures/${name}.dex`;
  }

  if (!outputPath) {
    outputPath = path.join(
      __dirname, '..', 'test', 'integration',
      `${name.replace(/-/g, '_')}.test.ts`
    );
  } else {
    outputPath = path.resolve(outputPath);
  }

  console.log(`[CRAFT][GenIntegrationTest][Info] Generating test: ${name}`);
  console.log(`[CRAFT][GenIntegrationTest][Info] Fixture: ${fixturePath}`);
  console.log(`[CRAFT][GenIntegrationTest][Info] Activity: ${activityClass}`);
  console.log(`[CRAFT][GenIntegrationTest][Info] Mode: ${useRuntime ? 'CraftRuntime' : 'Interpreter'}`);

  const testCode = useRuntime
    ? generateRuntimeTest(name, fixturePath, activityClass)
    : generateInterpreterTest(name, fixturePath, activityClass);

  // Ensure output directory exists
  const outDir = path.dirname(outputPath);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  if (fs.existsSync(outputPath)) {
    console.error(`[CRAFT][GenIntegrationTest][Error] File already exists: ${outputPath}`);
    console.error('Use --output to specify a different path');
    process.exit(1);
  }

  fs.writeFileSync(outputPath, testCode, 'utf-8');
  console.log(`\n[CRAFT][GenIntegrationTest][Success] Written to: ${outputPath}`);
}

main();
