#!/usr/bin/env ts-node
/**
 * CRAFT Gen Fixture - Skill #10
 * Generate DEX test fixtures for specific test scenarios.
 */

import * as fs from 'fs';
import * as path from 'path';

function printUsage(): void {
  console.log(`
[CRAFT][GenFixture] Test Fixture Builder

Usage: npm run gen-fixture <scenario> [options]

Options:
  --output <path>         Output path (default: test/fixtures/<scenario>.dex)
  --class <descriptor>    Custom class name
  --list                  List available scenarios
  --help                  Show this help

Scenarios:
  null-pointer       Method that triggers NullPointerException
  deep-inheritance   4-level class hierarchy with virtual dispatch
  static-init        Class with <clinit> static initializer
  array-ops          Array creation, fill, access, bounds error
  string-ops         String creation, StringBuilder usage
  all-opcodes        Uses key implemented opcodes (82 total)

Examples:
  npm run gen-fixture -- --list
  npm run gen-fixture null-pointer
  npm run gen-fixture deep-inheritance -- --output test/fixtures/deep.dex
`);
}

// Minimal DEX file builder that creates binary DEX data
// Uses the patterns from generate_test_fixtures.ts

class MinimalDexBuilder {
  private strings: string[] = [];
  private types: string[] = [];
  private methods: { classIdx: number; protoIdx: number; nameIdx: number }[] = [];
  private protos: { shortyIdx: number; returnTypeIdx: number; params: number[] }[] = [];
  private fields: { classIdx: number; typeIdx: number; nameIdx: number }[] = [];
  private classes: {
    typeIdx: number;
    superIdx: number;
    accessFlags: number;
    directMethods: { idx: number; accessFlags: number; code: number[] }[];
    virtualMethods: { idx: number; accessFlags: number; code: number[] }[];
  }[] = [];

  addString(s: string): number {
    const idx = this.strings.indexOf(s);
    if (idx >= 0) return idx;
    this.strings.push(s);
    return this.strings.length - 1;
  }

  addType(d: string): number {
    const idx = this.types.indexOf(d);
    if (idx >= 0) return idx;
    this.addString(d);
    this.types.push(d);
    return this.types.length - 1;
  }

  addProto(shorty: string, retType: string, paramTypes: string[] = []): number {
    const shortyIdx = this.addString(shorty);
    const returnTypeIdx = this.addType(retType);
    const params = paramTypes.map((p) => this.addType(p));
    this.protos.push({ shortyIdx, returnTypeIdx, params });
    return this.protos.length - 1;
  }

  addMethod(cls: string, name: string, shorty: string, retType: string, params: string[] = []): number {
    const classIdx = this.addType(cls);
    const nameIdx = this.addString(name);
    const protoIdx = this.addProto(shorty, retType, params);
    this.methods.push({ classIdx, protoIdx, nameIdx });
    return this.methods.length - 1;
  }

  addField(cls: string, name: string, type: string): number {
    const classIdx = this.addType(cls);
    const nameIdx = this.addString(name);
    const typeIdx = this.addType(type);
    this.fields.push({ classIdx, typeIdx, nameIdx });
    return this.fields.length - 1;
  }

  addClass(
    descriptor: string,
    superClass: string,
    accessFlags: number,
    directMethods: { idx: number; accessFlags: number; code: number[] }[],
    virtualMethods: { idx: number; accessFlags: number; code: number[] }[] = []
  ): void {
    this.classes.push({
      typeIdx: this.addType(descriptor),
      superIdx: this.addType(superClass),
      accessFlags,
      directMethods,
      virtualMethods,
    });
  }

  /** Build a binary DEX file. Returns simplified synthetic DexParser-compatible data. */
  buildDescription(): string {
    const lines: string[] = [];
    lines.push(`DEX Fixture Description`);
    lines.push(`Strings: ${this.strings.length}`);
    lines.push(`Types: ${this.types.length}`);
    lines.push(`Methods: ${this.methods.length}`);
    lines.push(`Classes: ${this.classes.length}`);
    lines.push('');

    for (const cls of this.classes) {
      lines.push(`Class: ${this.types[cls.typeIdx]}`);
      lines.push(`  Super: ${this.types[cls.superIdx]}`);
      for (const m of cls.directMethods) {
        const mid = this.methods[m.idx];
        lines.push(`  Direct: ${this.strings[mid.nameIdx]} (${m.code.length} insns)`);
      }
      for (const m of cls.virtualMethods) {
        const mid = this.methods[m.idx];
        lines.push(`  Virtual: ${this.strings[mid.nameIdx]} (${m.code.length} insns)`);
      }
    }

    return lines.join('\n');
  }

  /** Generate a TypeScript test helper file with the SyntheticDexBuilder calls */
  buildTestHelper(scenario: string): string {
    const lines: string[] = [];
    lines.push(`// Auto-generated fixture: ${scenario}`);
    lines.push(`// Generated by: npm run gen-fixture ${scenario}`);
    lines.push(`import { SyntheticDexBuilder, makeCode } from '../../integration/interpreter/test_helpers';`);
    lines.push('');
    lines.push(`export function build_${scenario.replace(/-/g, '_')}() {`);
    lines.push(`  const dex = new SyntheticDexBuilder();`);
    lines.push('');

    // Emit addString calls
    for (const s of this.strings) {
      lines.push(`  dex.addString('${s.replace(/'/g, "\\'")}');`);
    }
    lines.push('');

    // Emit addType calls
    for (const t of this.types) {
      lines.push(`  dex.addType('${t}');`);
    }
    lines.push('');

    // Emit addMethod calls
    for (let i = 0; i < this.methods.length; i++) {
      const m = this.methods[i];
      const proto = this.protos[m.protoIdx];
      const retType = this.types[proto.returnTypeIdx];
      const params = proto.params.map((p) => `'${this.types[p]}'`).join(', ');
      lines.push(`  dex.addMethod('${this.types[m.classIdx]}', '${this.strings[m.nameIdx]}', '${retType}', [${params}]);`);
    }
    lines.push('');

    // Emit addClass calls
    for (const cls of this.classes) {
      const desc = this.types[cls.typeIdx];
      const superDesc = this.types[cls.superIdx];
      const dm = cls.directMethods.map((m) => {
        return `{ methodIdx: ${m.idx}, accessFlags: 0x${m.accessFlags.toString(16)}, code: makeCode([${m.code.join(', ')}], ${Math.max(4, m.code.length)}) }`;
      });
      const vm = cls.virtualMethods.map((m) => {
        return `{ methodIdx: ${m.idx}, accessFlags: 0x${m.accessFlags.toString(16)}, code: makeCode([${m.code.join(', ')}], ${Math.max(4, m.code.length)}) }`;
      });
      lines.push(`  dex.addClass('${desc}', '${superDesc}', {`);
      lines.push(`    accessFlags: 0x${cls.accessFlags.toString(16)},`);
      if (dm.length > 0) {
        lines.push(`    directMethods: [${dm.join(', ')}],`);
      }
      if (vm.length > 0) {
        lines.push(`    virtualMethods: [${vm.join(', ')}],`);
      }
      lines.push(`  });`);
    }

    lines.push('');
    lines.push(`  return dex.build();`);
    lines.push(`}`);
    return lines.join('\n');
  }
}

// ─── Scenarios ───

interface Scenario {
  name: string;
  description: string;
  build: () => MinimalDexBuilder;
}

const scenarios: Scenario[] = [
  {
    name: 'null-pointer',
    description: 'Method that triggers NullPointerException via iget on null',
    build: () => {
      const dex = new MinimalDexBuilder();
      // Class with method that does iget on v0 (which is int 0 = null)
      const methodIdx = dex.addMethod('LNullTest;', 'trigger', 'V', 'V');
      const fieldIdx = dex.addField('LNullTest;', 'value', 'I');
      dex.addClass('LNullTest;', 'Ljava/lang/Object;', 0x0001, [
        {
          idx: methodIdx,
          accessFlags: 0x0009, // public static
          code: [
            0x0012,       // const/4 v0, 0 (null)
            0x0052 | (0x00 << 8) | (0x00 << 12), // iget v0, v0, field@0
            fieldIdx,
            0x000e,       // return-void
          ],
        },
      ]);
      return dex;
    },
  },
  {
    name: 'deep-inheritance',
    description: '4-level class hierarchy: D extends C extends B extends A',
    build: () => {
      const dex = new MinimalDexBuilder();
      // A.greet() -> returns void
      const aGreet = dex.addMethod('LA;', 'greet', 'V', 'V');
      // B overrides nothing, C.greet() overrides, D extends C
      const cGreet = dex.addMethod('LC;', 'greet', 'V', 'V');

      dex.addClass('LA;', 'Ljava/lang/Object;', 0x0001, [], [
        { idx: aGreet, accessFlags: 0x0001, code: [0x000e] },
      ]);
      dex.addClass('LB;', 'LA;', 0x0001, [], []);
      dex.addClass('LC;', 'LB;', 0x0001, [], [
        { idx: cGreet, accessFlags: 0x0001, code: [0x000e] },
      ]);
      dex.addClass('LD;', 'LC;', 0x0001, [], []);
      return dex;
    },
  },
  {
    name: 'static-init',
    description: 'Class with <clinit> static initializer',
    build: () => {
      const dex = new MinimalDexBuilder();
      const fieldIdx = dex.addField('LStaticInit;', 'counter', 'I');
      const clinit = dex.addMethod('LStaticInit;', '<clinit>', 'V', 'V');
      const getVal = dex.addMethod('LStaticInit;', 'getCounter', 'V', 'I');

      dex.addClass('LStaticInit;', 'Ljava/lang/Object;', 0x0001, [
        {
          idx: clinit,
          accessFlags: 0x10008, // static constructor
          code: [
            0x1312,       // const/16 v1, 42
            42,
            0x0067 | (0x01 << 8), // sput v1, field@0
            fieldIdx,
            0x000e,       // return-void
          ],
        },
      ], [
        {
          idx: getVal,
          accessFlags: 0x0009, // public static
          code: [
            0x0060,       // sget v0, field@0
            fieldIdx,
            0x000f,       // return v0
          ],
        },
      ]);
      return dex;
    },
  },
  {
    name: 'array-ops',
    description: 'Array creation, fill, and access patterns',
    build: () => {
      const dex = new MinimalDexBuilder();
      const main = dex.addMethod('LArrayOps;', 'main', 'V', 'V');

      // Simple method that returns void - uses const/4 and return-void
      dex.addClass('LArrayOps;', 'Ljava/lang/Object;', 0x0001, [
        {
          idx: main,
          accessFlags: 0x0009,
          code: [
            0x3012,       // const/4 v0, 3 (array length)
            0x000e,       // return-void
          ],
        },
      ]);
      return dex;
    },
  },
  {
    name: 'string-ops',
    description: 'String creation and const-string usage',
    build: () => {
      const dex = new MinimalDexBuilder();
      const helloIdx = dex.addString('Hello');
      const worldIdx = dex.addString('World');
      const main = dex.addMethod('LStringOps;', 'main', 'V', 'V');

      dex.addClass('LStringOps;', 'Ljava/lang/Object;', 0x0001, [
        {
          idx: main,
          accessFlags: 0x0009,
          code: [
            0x001a,       // const-string v0, string@hello
            helloIdx,
            0x011a,       // const-string v1, string@world
            worldIdx,
            0x000e,       // return-void
          ],
        },
      ]);
      return dex;
    },
  },
  {
    name: 'all-opcodes',
    description: 'Uses key implemented opcodes in one method',
    build: () => {
      const dex = new MinimalDexBuilder();
      const main = dex.addMethod('LOpcodeTest;', 'main', 'V', 'V');
      const strIdx = dex.addString('test');

      dex.addClass('LOpcodeTest;', 'Ljava/lang/Object;', 0x0001, [
        {
          idx: main,
          accessFlags: 0x0009,
          code: [
            0x0000,       // nop
            0x0012,       // const/4 v0, 0
            0x5012,       // const/4 v0, 5
            0x001a,       // const-string v0, string@0
            strIdx,
            0x000e,       // return-void
          ],
        },
      ]);
      return dex;
    },
  },
];

function listScenarios(): void {
  console.log('[CRAFT][GenFixture] Available scenarios:\n');
  for (const s of scenarios) {
    console.log(`  ${s.name.padEnd(20)} ${s.description}`);
  }
  console.log('');
}

function main(): void {
  const args = process.argv.slice(2);

  if (args.length === 0 || args.includes('--help')) {
    printUsage();
    process.exit(0);
  }

  if (args.includes('--list')) {
    listScenarios();
    process.exit(0);
  }

  let scenarioName = '';
  let outputPath = '';
  let customClass = '';

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--output':
        outputPath = args[++i] || '';
        break;
      case '--class':
        customClass = args[++i] || '';
        break;
      default:
        if (!args[i].startsWith('-') && !scenarioName) {
          scenarioName = args[i];
        }
        break;
    }
  }

  const scenario = scenarios.find((s) => s.name === scenarioName);
  if (!scenario) {
    console.error(`[CRAFT][GenFixture][Error] Unknown scenario: ${scenarioName}`);
    console.error(`Use --list to see available scenarios`);
    process.exit(1);
  }

  if (!outputPath) {
    outputPath = path.join(__dirname, '..', 'test', 'fixtures', `${scenarioName}.ts`);
  } else {
    outputPath = path.resolve(outputPath);
  }

  console.log(`[CRAFT][GenFixture][Info] Building scenario: ${scenario.name}`);
  console.log(`[CRAFT][GenFixture][Info] Description: ${scenario.description}`);

  const builder = scenario.build();

  // Generate the test helper TypeScript file
  const helperCode = builder.buildTestHelper(scenarioName);

  // Ensure output directory exists
  const outDir = path.dirname(outputPath);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, helperCode, 'utf-8');
  console.log(`[CRAFT][GenFixture][Info] Written to: ${outputPath}`);
  console.log('');
  console.log('Fixture description:');
  console.log(builder.buildDescription());
}

main();
